services:
  api:
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://fastapi_test:fastapi_test_password@db/fastapi_test_db

  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi_test_db
      - POSTGRES_PASSWORD=fastapi_test
      - POSTGRES_DB=fastapi_test_password